// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxF6GWnh5xP0k1t5ZzZgNkZePejsD5_IU',
    appId: '1:349287983571:web:d81fe515e8d1094246e726',
    messagingSenderId: '349287983571',
    projectId: 'e-commerce-943fd',
    authDomain: 'e-commerce-943fd.firebaseapp.com',
    storageBucket: 'e-commerce-943fd.firebasestorage.app',
    measurementId: 'G-F7SPQCJEZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ2A7OXx5P53ZO8Og6lLC9RO_cSeOA4MY',
    appId: '1:349287983571:android:740c75f137c9f25646e726',
    messagingSenderId: '349287983571',
    projectId: 'e-commerce-943fd',
    storageBucket: 'e-commerce-943fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_qS_8ghRrq68Rs1r8Z6dF_i4cGu-6FU4',
    appId: '1:349287983571:ios:118fb66ef844a48746e726',
    messagingSenderId: '349287983571',
    projectId: 'e-commerce-943fd',
    storageBucket: 'e-commerce-943fd.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_qS_8ghRrq68Rs1r8Z6dF_i4cGu-6FU4',
    appId: '1:349287983571:ios:118fb66ef844a48746e726',
    messagingSenderId: '349287983571',
    projectId: 'e-commerce-943fd',
    storageBucket: 'e-commerce-943fd.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxF6GWnh5xP0k1t5ZzZgNkZePejsD5_IU',
    appId: '1:349287983571:web:09216f90fcfe303946e726',
    messagingSenderId: '349287983571',
    projectId: 'e-commerce-943fd',
    authDomain: 'e-commerce-943fd.firebaseapp.com',
    storageBucket: 'e-commerce-943fd.firebasestorage.app',
    measurementId: 'G-98LJJD51M7',
  );
}
